version: 2
updates:
  - package-ecosystem: "gitsubmodules"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "alkiranet/alkira-eng-routing"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "alkiranet/alkira-eng-routing"
    open-pull-requests-limit: 10
